on: [push,pull_request]
name: Continuous Deployment
jobs:
  CD:
    name: Continuous Deployment for React and Java Project
    runs-on: [self-hosted]
    steps:
    - name: CD for TQS 
      run: |
        echo "Hello World!"
