on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Continuous Deployment
jobs:
  Tests:
    name: Running unit,integration and web tests
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Pull repository
        run: |
          git -C ~/TQS_2/ pull;
      - name: Unit and Integration
        run: 
          mvn -f ~/TQS_2/JustLikeHomeStarter verify -Dtest=!WebPlatformTesting
      - name: Functional Test
        working-directory: ~/TQS/Frontend/JustLikeHome/example
        run: |
          npm ci;
          npm start;
          mvn -f ~/TQS_2/JustLikeHomeStart verify -Dtest=WebPlatformTesting
  CD:
    needs: [Tests]
    name: Continuous Deployment for React and Java Project
    runs-on: [self-hosted]
    steps:
    - name: Docker clean
      run: |
        docker ps -aq;
        docker kill $(docker ps -aq) || true;
        docker rm $(docker ps -aq) || true;
        docker volume ls -qf dangling=true;
        docker volume rm $(docker volume ls -qf dangling=true) || true;
        docker rmi $(docker image ls) || true;
    - name: Server pull repository
      run: |
        git -C ~/TQS_2/ pull;
    - name: CD for Spring-Boot Backend  
      run: |
        docker build --tag "backend" ~/TQS_2/JustLikeHomeStarter;
        docker run -p 8080:8080 -d backend;
    - name: CD for React Frontend
      run: |
        docker build --tag "frontend" ~/TQS_2/Frontend;
        docker run -p 80:3000 -d frontend;
