on: [push,pull_request]
name: Tests w/ sonarcloud
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Test and SonarCloud 
      run: 
        mvn -f JustLikeHomeStarter verify -Dtest=!WebPlatformTesting sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=MotaMiguel_TQS_2 -Dsonar.organization=tqs-project -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
